spring.application.name=apexmotion
#Sever
server.port = 8080
#Ket noi postgres
spring.datasource.url = jdbc:postgresql://localhost:5432/apexmotion_db
spring.datasource.username = apexmotion
spring.datasource.password = apexmotion123
spring.datasource.driver-class-name=org.postgresql.Driver
#Setup Hibernate
spring.jpa.hibernate.ddl-auto = update
#Hien cau SQL trong console
spring.jpa.show-sql = true
#Format SQL
spring.jpa.properties.hibernate.format_sql = true
#Dialect cho postgresql
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#Setup Redis
spring.data.redis.host = localhost
spring.data.redis.port = 6379
#Setup JWT
jwt.secret=mySecretKeyAtLeast256BitsLongForHS256AlgorithmApexMotion2026
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000